### ISSUE TITLE
Require data for Tutorial 15: Transfer Learning

### ISSUE THREAD

**Issue by harshdhamecha** [python-engineer/pytorchTutorial#18]
Hello Patrick, Can you please update the repo with the data used in tutorial 15?

**Comment by NaivedeJiang** [comment]
Same issue here. I can't find data for Lesson 15.

**Comment by ggck43** [comment]
This is the link of the dataset: https://www.kaggle.com/datasets/gauravduttakiit/ants-bees

**Comment by VincentTsai0601** [comment]
I can't find the dataset either.

**Comment by patrickloeber** [comment]
It's here: https://download.pytorch.org/tutorial/hymenoptera_data.zip

**Comment by patrickloeber** [comment]
Added the link (see comment above).

**Comment by patrickloeber** [comment]
Added the link (see comment above).
